### ISSUE TITLE
JS namespace

### ISSUE THREAD

**Issue by rappen** [davidyack/Xrm.Tools.CRMWebAPI#16]
There is no namespace for the JS library, just the "class" name `CRMWebAPI`.
To reduce risk of "colliding code" it might be better to use a "namespace" for the "class".
Perhaps something like this?

```
if (typeof (ColoradoTech) === "undefined") { ColoradoTech = {}; }
if (typeof (ColoradoTech.Xrm) === "undefined") { ColoradoTech.Xrm = {}; }
if (typeof (ColoradoTech.Xrm.Tools) === "undefined") { ColoradoTech.Xrm.Tools = {}; }
ColoradoTech.Xrm.Tools.CRMWebAPI = (function () {
  ...
})();
```

The call to construct an instance would then be
`var crmAPI = new ColoradoTech.Xrm.Tools.CRMWebAPI(apiconfig);`

**Comment by davidyack** [comment]
Yeah probably would have used Xrm.Tools - that said adding it now would break compatibility with anyone using it.  Any suggestion on how to add it and not break others?

**Comment by rappen** [comment]
It could be possible to add
``  CRMWebAPI = Xrm.Tools.CRMWebAPI:``
at the end of the file.

Or put that line in a separate file to be included only if you need backward compatibility...
Not a very neat solution though.

**Comment by davidyack** [comment]
For now I think we are going to leave it as is, I'm not aware of this causing anyone any problems and if it does they are welcome to fork it and adjust the namespace
