### ISSUE TITLE
IE11 Promise supported ?

### ISSUE THREAD

**Issue by phuocle** [davidyack/Xrm.Tools.CRMWebAPI#20]
I get an error: **'Promise' is undefined** from CrmWebAPI.js

**Comment by davidyack** [comment]
if you look at the sample web resource - we recommend a polyfill for to ensure promises are available in the different browsers -

e.g. 
<script src="https://www.promisejs.org/polyfills/promise-7.0.4.min.js"></script>

You can see a full sample web resource here - https://github.com/davidyack/Xrm.Tools.CRMWebAPI/blob/master/JS/Examples/SimpleCRMWebResource/SimpleCRMWebResource.html

Let us know if that does not solve your problem.

**Comment by phuocle** [comment]
@davidyack Thanks, everything now ok.
