### ISSUE TITLE
ExecuteAction is not working in JS 

### ISSUE THREAD

**Issue by sigurdGeerts** [davidyack/Xrm.Tools.CRMWebAPI#21]
Hello,

I'm using your CRMWebAPI in JS and i want to use the function "ExecuteAction". I have created the following lines of code :

 TestFunction: function (isoCode,phone_number)
    {
        var params = {
            "PhoneNumber": phone_number,
            "Country": isoCode
        };

```
    Infront.account.CrmApi().ExecuteAction("ng_AccountValidatePhoneNumber", params).then(function (r) {
        alert(r);
    }, function (e) {
        alert(e);
    });
}
```

But when the code is executed i get the following error : Resource not found for the segment 'ng_AccountValidatePhoneNumber'.

What i'm doing wrong ? Are there more examples of using an action ?

Kind regards,

Sigurd Geerts

**Comment by sigurdGeerts** [comment]
Issue is resolved :-)

**Comment by MscrmTools** [comment]
@sigurdGeerts Please explain what was wrong to help people with the same error

**Comment by sigurdGeerts** [comment]
My action was not a global action and by changing it to a global action it works fine

**Comment by davidyack** [comment]
Yeah to call it with a entity bound action you would add e.g. "accounts","<guid>"  I will see if we can add a wiki page with a few action examples

**Comment by davidyack** [comment]
An example of calling an entity bound action was added here - https://github.com/davidyack/Xrm.Tools.CRMWebAPI/wiki/Action-Examples
