### ISSUE TITLE
Make a TypeScript version

### ISSUE THREAD

**Issue by con-ssc** [davidyack/Xrm.Tools.CRMWebAPI#22]
This would fulfill #19 too I think. Since this already looks like a class output from typescript, maybe you have that already, otherwise I would suggest to make one in conjunction with the xrm.d.ts from definitely typed.

**Comment by davidyack** [comment]
Great idea, we actually have a prototype in the works on this, just haven't had the time to finish it yet

**Comment by con-ssc** [comment]
maybe 23e180e helps to start it

**Comment by davidyack** [comment]
Ah Nice didn't see you submitted a pull - cool will check it out

**Comment by davidyack** [comment]
So we decided as a first step to include a ts definition - if you install the npm package now it is included in the installed package.  There is a good chance we might move to maintenance of the lib in TS in the future just not ready to commit to that yet.  Hope that helps!
