### ISSUE TITLE
Missing annotations

### ISSUE THREAD

**Issue by con-ssc** [davidyack/Xrm.Tools.CRMWebAPI#23]
as far as I can see it the option for annotations is missing.

**Comment by davidyack** [comment]
You can request annotations using the following syntax on the query options on Get and GetList

 var queryOptions = { Top:10 , 
            FormattedValues:true, 

You can find more query examples here - https://github.com/davidyack/Xrm.Tools.CRMWebAPI/wiki/Query-Examples

Let us know if you think there are examples we should add!
Thanks,
Dave

**Comment by con-ssc** [comment]
While transcribing it to typescript I found that what it wasn't clear to me from watching the httprequests
