### ISSUE TITLE
Maybe use SDK functions

### ISSUE THREAD

**Issue by con-ssc** [davidyack/Xrm.Tools.CRMWebAPI#25]
It may be better to use the general function from the sdk

https://msdn.microsoft.com/en-us/library/mt742431.aspx

**Comment by davidyack** [comment]
Which function from the SDK are you referring to ?

**Comment by con-ssc** [comment]
The one in the link to handle all actions. The xmlhttprequest

**Comment by davidyack** [comment]
are you referring to the request function?

**Comment by con-ssc** [comment]
yes exactly

**Comment by davidyack** [comment]
Guess I'm not sure what you think we would gain from using that, it is a sample, you are welcome to use it instead, but exposing a generic request type method isn't the goal of this API helper

**Comment by con-ssc** [comment]
I think for ppl who work with this, and try to switch it would be easier if the behavior would be familar.

**Comment by JimDaly** [comment]
SDK samples are not trying to provide a re-usable library. The Sdk.request function in the SDK is _intentionally minimalist_. There are many different ways people can code these requests and a lot of it is a matter of preference. There is no one right answer.

What David has created here is a very elegant wrapper around the same native XMLHttpRequest which has a better overall developer experience, IMHO.
