### ISSUE TITLE
Guidance on WebAPI

### ISSUE THREAD

**Issue by mohsinonxrm** [davidyack/Xrm.Tools.CRMWebAPI#27]
Hi David,

This is not about any issue in CRMWebAPI but rather a discussion on it. I'm looking for some guidance for real world applications that currently use the SOAP endpoint to eventually switch to WebAPI. Right now, looking at the SDK samples and this WebAPI, it appears the solution won't look clean, everything is pretty loosely coupled. Also, it appears to be more work will need to do done to process the "Messages"/Requests WinOpportunity, QualifyLead among others, as you have to create the request yourself and load in the parameters. The OData style queries in code, it's a mess. Your solution is the only one I came across to do bulk Create/Update operations using MultipartContent.

I'm not sure what feedback Microsoft CRM team is getting but I don't think they should remove the 2011 endpoint.

Your thoughts?

**Comment by davidyack** [comment]
What type of application are you building?

**Comment by mohsinonxrm** [comment]
Thanks for the quick reply David. I'm talking about any application in specific. It is more of a general question. Could be anything, web portal, a utility to load in data/integration. Basically anything that is outside CRM using the SDK.

**Comment by davidyack** [comment]
ok, that helped I wanted to confirm you were not talking plugins.  Honestly, most of Microsoft's products are going to REST based APIs that tend to be more loosely coupled and are callable by a broader set of languages.  A few thoughts.

-  There are libraries that have stronger typing e.g. OData Client for C# and the associated T4 template generator
- Even though this API helper is intended to be pretty lightweight, you can still use typed object in C# - we don't provide a generator
- For C#, Jim Daly has published a sample that will generate JavaScript  here https://github.com/JimDaly/CRMJSWebAPIServiceUtil
- Actions can be called now from the Web API e.g. WinOpportunity etc.  There are a few that are not supported right now and they are looking to close the gap
- Some scenarios you could consider using Custom Actions backed by the logic in a plug-in, shifting chatty calls to the server than back/forth to the client.

Hope that helps, 
Dave

**Comment by mohsinonxrm** [comment]
yeah, for plug-ins and workflows I think I've either read it on MSDN or CRM Team blog or some session that Microsoft will just update the assemblies and all we'll have to do is recompile our projects with the latest dlls.

Regarding other points, I don't have a problem with JObject, I've always used the Entity object anyway. Only used CrmSvcUtil once with CRM 4.0 8 ~ 9 years ago.

If you see the SDK WebAPI sample, they've shown on how to call functions and actions (bound and unbound) and it is not very consistent, some attributes/members have different naming convention while others (the entity objects) have all lower case.

Anyway, I hope you keep on updating the API wrapper/helper as I think our only option right now is to either use this or write our own.

I just wanted to know what others think about the new WebAPI, so thanks for the helpful reply.
