### ISSUE TITLE
C# Add support for OData.Bind for relationship association 

### ISSUE THREAD

**Issue by davidyack** [davidyack/Xrm.Tools.CRMWebAPI#3]

**Comment by davidyack** [comment]
this should be possible closing for now

**Comment by EkoZuluDev** [comment]
Hi David, is there documentation about how to associate in C#?

**Comment by davidyack** [comment]
What type of relationship are you trying to create N:N or 1:N/N:1

**Comment by EkoZuluDev** [comment]
For starters N:N, just filling the related field with a existing guid is not sufficient.

I would not say no to extra information about 1:N/N:1 👍

**Comment by davidyack** [comment]
Latest 1.0.24 just published includes the following two methods

api.Associate("accounts", accountID, "primarycontactid", "contacts", contactID);

api.DeleteAssociation("accounts", accountID, "primarycontactid", "contacts", contactID);


For N:1 you can also set via the Update method

**Comment by davidyack** [comment]
I should add an example - basically you set a property like the following

"primarycontactid@odata.bind":"/contacts(<insert guid here to existing contact>)"

**Comment by EkoZuluDev** [comment]
Hi David , I do not know if this is the place to ask a question concerning Association
 I can't figure why it does not work in some cases.

For example this does not work for me. 
api.Associate("contacts", createdId, "my_fieldid", "my_entitiesA", guid).Result; 
I get the error " One or more errors occurred. (The URI segment '$ref' is invalid after the segment 'my_fieldid'.)"

This however works 
  api.Associate("my_entitiesB", createdId, "my_fieldid", "my_entitiesA", guid);

Any pointers to where should investigate?
