### ISSUE TITLE
Promises for IE 11

### ISSUE THREAD

**Issue by Stanzarectah** [davidyack/Xrm.Tools.CRMWebAPI#32]
Since this is not supported in IE 11 how do I make this work in your code?

Thanks

**Comment by davidyack** [comment]
Thanks for reaching out, if you are working with older browsers you need to use a polyfill, an example of that is https://www.promisejs.org - they have a cdn version of it here - https://www.promisejs.org/polyfills/promise-7.0.4.min.js  - you can see a full example of a very simple web resource here - https://github.com/davidyack/Xrm.Tools.CRMWebAPI/blob/master/JS/Examples/SimpleCRMWebResource/SimpleCRMWebResource.html

Hope that helps
Dave

**Comment by Stanzarectah** [comment]
Awesome thanks for the example David, I have got it to work.

**Comment by davidyack** [comment]
Great to hear
