### ISSUE TITLE
Calling Global Custom Actions

### ISSUE THREAD

**Issue by CHTEEVE** [davidyack/Xrm.Tools.CRMWebAPI#35]
I'm having issue when trying to call a global custom action. I don't know if it is because I'm not using the tool properly or not. Error message is : 

An unexpected 'PrimitiveValue' node was found when reading from the JSON reader. A 'StartObject' node was expected.\",\"innererror\":{\r\n      \"message\":\"An unexpected 'PrimitiveValue' node was found when reading from the JSON reader. A 'StartObject' node was expected.\",\"type\":\"Microsoft.Crm.CrmHttpException\",\"stacktrace\":\"   at Microsoft.Crm.Extensibility.OData.CrmODataUtilities.ValidateInputParameters(ModelStateDictionary controllerModelState)\\r\\n

**Comment by CHTEEVE** [comment]
my code is :
  crmAPI.ExecuteAction('gdi_ExtrantsComptesBannieres',null, null, null).then(function (result) {
                                    alert('yeah');
                                }, function (error) { alert(error.responseText); });

**Comment by davidyack** [comment]
Can you let me know what the parameters look like on the function gdi_ExtrantscoptesBanneries - it looks like you don't have any configured

**Comment by CHTEEVE** [comment]
It's working when I'm putting an empty object instead of null

**Comment by davidyack** [comment]
Yes, that makes sense, I believe in all variations of the library it is expecting an object - will leave this open to change to handle null being passed - but for now the work around is as you indicated passing an empty object.  Thanks for sharing!
