### ISSUE TITLE
Clear Lookup Value with Update function

### ISSUE THREAD

**Issue by CHTEEVE** [davidyack/Xrm.Tools.CRMWebAPI#36]
Hi, I'm trying to remove a lookup value with Update function, it's not causing any error but it did not clear the field as Well.

Snippet:
var lookupString ;
u["gdi_Acheteur1Id@odata.bind"] = lookupString;
crmAPI.Update("gdi_valeur_extrants", data.model.gdi_valeur_extrantid, u).then(function(){
                          
                       },
                         function (error) {
                             alert(error.responseText);
                         });

I'm wondering if I could use the **DeleteAssociation** function instead of Update when I need to do this kind of action.

**Comment by davidyack** [comment]
Yes, DeleteAssocation would be the best to remove the association - you should be able to use the syntax you have with Create or Update to do the association but I don't believe you can remove the association that way currently.
