### ISSUE TITLE
Create method on CRMWebAPI class returns an empty guid when there are uppercase characters in the CRM WebAPI URL

### ISSUE THREAD

**Issue by emtea** [davidyack/Xrm.Tools.CRMWebAPI#37]
#### Create method on the CRMWebAPI class returns an empty Guid when there are uppercase characters in the CRM WebAPI URL

This was tested using .net core class library and problem is most likely related to the following helper method:
`private static Guid GetEntityIDFromResponse(string fullUrl, HttpResponseMessage response)`

as the logic in the helper relies on the fullUrl.ToLower() string:
`idString = idString.Replace(fullUrl.ToLower(), "").Replace("(", "").Replace(")", "");`

Workaround:
When initiating the CRMWebAPI instance, provide the CRM WebAPI URL in lowercase only.

**Comment by davidyack** [comment]
In 1.0.12 and later the url you provide is lower cased prior to the extract of the ID, which version are you using that you see it returning an empty id
