### ISSUE TITLE
Error with ExecuteAction

### ISSUE THREAD

**Issue by ChrisKoenig** [davidyack/Xrm.Tools.CRMWebAPI#38]
I'm getting an error when I execute the action associated with running a full-text search on the KnowledgeArticle entities:

```
function getArticles(phrase, fn) {
    var action = "FullTextSearchKnowledgeArticle";
    var params = {
        'SearchText': phrase,
        'StateCode': 1,
        'QueryExpression': {
            'ColumnSet': ['title', 'description', 'articlepublicnumber'],
            'EntityName' : 'knowledgearticle'
        }
    };
    crmApi.ExecuteAction(action, params).then(function(r) {
        fn(r);
    }, function(e) {
        logError('getArticles', e);
    });
}
```
The error returned is:
```
The property 'ColumnSet' does not exist on type 'Microsoft.Dynamics.CRM.QueryBase'. Make sure to only use property names that are defined by the type.
```
What I need to be able to do is specify the QueryExpression parameter as a type `Microsoft.CRM.Dynamics.QueryExpression` instead of it's base class, `Microsoft.Dynamics.CRM.QueryBase`.  

Any ideas on how to do this? Hopefully I'm just missing something that should be obvious...

**Comment by davidyack** [comment]
Hey Chris - have you tried this in a generic tool like Postman to see if it works? I've not used this particular action but will check around to see if anyone has successfully used it

**Comment by ChrisKoenig** [comment]
No, I've not tried that, but I will look into it. I'm suspecting that this particular function is going to be tricky as it takes one of several types for QueryExpression per the documentation, all subclasses of QueryBase and I don't know if JavaScript can "understand" subclasses in the same way that languages like C# can.  Do you know how to do this?

**Comment by davidyack** [comment]
I would try adding '@odata.type':'mscrm.QueryExpression' to the QueryExpression object - I sent a query off to see if Microsoft has an example of the JSon for this particular action

**Comment by ChrisKoenig** [comment]
Using this notation worked - sort of... now it doesn't error out, but I get no records returned in the results. I think this problem   has to do with what is in my QueryExpression for Criteria and Filter. I will play with it more and see, but this did the trick for the immediate error I was experiencing.

Cheers!
Chris
_____________________________

**Comment by ChrisKoenig** [comment]
I was finally able to get this working. There is [at least one bug with the Javascript-compatible syntax for the API](https://www.bountysource.com/issues/42063625-odata-7-0-0-libs-do-not-support-a-array-of-untyped-primitive-values) itself, but the action is now working. Here's my sample code to help close this loop (note: my sample is part of a BotFramework project, and this is coming from my CRM helper class):

```
exports.getArticles = function (session, keyword) {
    return new Promise((resolve, reject) => {
        _authenticate(crmServerUrl, crmUsername, crmPassword, adalHostUrl, adalClientId)
            .then((api) => {
                var fieldArray = ["title", "isinternal", "description", "articlepublicnumber", "modifiedon", "statecode", "keywords"];
                var action = "FullTextSearchKnowledgeArticle";
                var parms = {
                        'SearchText': keyword,
                        'UseInflection': false,
                        'RemoveDuplicates': true,
                        'StateCode': 3,
                        'QueryExpression': {
                            '@odata.type': "Microsoft.Dynamics.CRM.QueryExpression",
                            'EntityName': 'knowledgearticle',
                            'ColumnSet': {
                                '@odata.type': "Microsoft.Dynamics.CRM.ColumnSet",
                                'Columns': fieldArray,
                            },
                            "PageInfo": {
                                "Count": 10,
                                "ReturnTotalRecordCount": true
                            },
                            "Orders": [{
                                "AttributeName": "modifiedon",
                                "OrderType": "Descending"
                            }]
                        }
                    };

                api.ExecuteAction(action, parms).then(
                    function (output) {
                        resolve(output.value);
                    },
                    function (error) {
                        reject(error);
                    });
            });
    });
}
```

What was missing from before was the PageInfo entity. Once I supplied that, I started getting results back.
