### ISSUE TITLE
Remove Content Length for XmlHttpRequest Header?

### ISSUE THREAD

**Issue by daryllabar** [davidyack/Xrm.Tools.CRMWebAPI#39]
Chrome gives this error from line 422.  Any reason it's needed?  Maybe it should just be removed.?

**Comment by davidyack** [comment]
What error?  line 422 is req.setRequestHeader("OData-MaxVersion", "4.0");?

**Comment by daryllabar** [comment]
Sorry I was on the previous version.  Line 427:

req.setRequestHeader("Content-Length", payload.data.length);

Lattimer's "CRM REST Builder" doesn't include it either...
