### ISSUE TITLE
 Add support for server paging to GetList

### ISSUE THREAD

**Issue by davidyack** [davidyack/Xrm.Tools.CRMWebAPI#4]

**Comment by davidyack** [comment]
GetList in C# is doing this using the NextLink when provided by the server

To test use .GetList("accounts") which will return about 6-7k accounts

**Comment by davidyack** [comment]
this needs to be done for js,php,python and node

**Comment by KhashRastin** [comment]
I am not able to get the paging to work? is there eny example on how you can test it? and  can you specify "odata.maxpagesize" somehow?

**Comment by davidyack** [comment]
The API handles server paging for you, no work required, as such we don't expose the maxpagesize setting - it is controlled by the server.  The JavaScript version does support PageAction which is a method that can process the records as each page is retrieved.  What problem are you having?

**Comment by KhashRastin** [comment]
Hi David thank you for answering but I think i found the problem, the @odata.nextLink doesnt seem to 
be available when you use a fetchXML query. Are you supposed the old way with pagecookies with fetchXML?

**Comment by davidyack** [comment]
@KhashRastin  with FetchXML you should be able to use page and count on the Fetch attribute.  We don't currently support the annotation Microsoft.Dynamics.CRM.fetchxmlpagingcookie  - but if you want to put in a new issue asking for that support I will see what it would take to add it - but I would appreciate if you start a new issue for it :) Thanks!
