### ISSUE TITLE
Delete Field syntax?

### ISSUE THREAD

**Issue by daryllabar** [davidyack/Xrm.Tools.CRMWebAPI#40]
Refer to this [article](https://community.dynamics.com/crm/b/crminogic/archive/2016/04/15/how-to-delete-record-field-value-using-the-web-api-in-dynamics-crm): 

Looks like clearing (aka nulling, aka deleting) a field in CRM isn't always possible with the patch request (I believe this is only for Entity-References).  The DeleteAssociation appears to implement this using the Delete call which I believe to be correct and a requirement for N:N, but for N:1, I don't believe as much information is required.  Just the field and $ref `"/api/data/v8.0/accounts(1DD18913-11CB-E511-80D2-C4346BDC11C1)/primarycontactid/$ref"`

Could this shorter syntax get added to the library?

If you'd like me to just submit a PR, let me know.

**Comment by davidyack** [comment]
Bottom line yes, I believe this was intended to have ToEntity/ToID be optional in the case of a single value lookup property - it just wasn't implemented in the formatting of the URL used on the delete - we should adjust that 

You are correct for N:N both are required, and it is also required if you are coming from the 1:N side which is considered a collection property as well.  From the N:1 side it is a single value and can use the shorthand syntax you described

**Comment by daryllabar** [comment]
So you're going to implement?

**Comment by davidyack** [comment]
Yes

**Comment by daryllabar** [comment]
Do you need me to update the td file?

**Comment by davidyack** [comment]
This has now been published in 1.3.5

**Comment by KhashRastin** [comment]
Is this implemented in the dot.net version can only find the fix in the js library?

**Comment by nzkelvin** [comment]
> Is this implemented in the dot.net version can only find the fix in the js library?

I had a quick look at the source code. It looks like he fixed the issue for the dot.net version as well.
