### ISSUE TITLE
Update fails when passing false as upsert parameter

### ISSUE THREAD

**Issue by wawojr** [davidyack/Xrm.Tools.CRMWebAPI#42]
When expecting to perform an update only, passing false as the upsert parameter causes an exception of 'Id ... already exists'. 

When passing false the header is 'If-None-Match', shouldn't this be 'If-Match'?

**Comment by ChrisKoenig** [comment]
I was getting the same error on update only… What is the proper way to format that request?

**Comment by wawojr** [comment]
I believe the line in the api Update function needs to be changed from 
`if (Upsert == false) payload["headers"]["If-None-Match"] = "*";`
to
`if (Upsert == false) payload["headers"]["If-Match"] = "*";`

**Comment by davidyack** [comment]
Ok, by default upsert is enabled, saying Upsert = false meaning you don't want to upsert causes If Match = * to be added to the header to not allow insert if already exists

If None Match is used if you want to prevent update

See https://msdn.microsoft.com/en-us/library/mt607711.aspx#bkmk_limitUpsertOperations

**Comment by ChrisKoenig** [comment]
So if I just want an update, and NOT allow insert, what is the proper way to call the method?

**Comment by davidyack** [comment]
And yes, you are correct, it looks like this is correct in the C# API but not correct in JS - will see about getting that resolved

**Comment by davidyack** [comment]
My recommendation for right now is to leave it upsert=true , which won't cause problems if you are updating records that exist, the idea is turning off upsert really is only needed if you think it might have been deleted and you don't want to re-create it

**Comment by wawojr** [comment]
Yeah, I'm working with existing client code, so I just modified my call to pass true. There are other libraries utilizing the api so I definitely did not make any changes to it. 

Thanks David.

**Comment by davidyack** [comment]
This has been resolved in the latest release 1.3.5
