### ISSUE TITLE
Format CRM Response

### ISSUE THREAD

**Issue by RafaelCavazza** [davidyack/Xrm.Tools.CRMWebAPI#51]
Hi!

Have you considered using some sort of return object? 

The Dynamic object is great for converting into JSON and sending data, but it complicated when we need to check if some field is present.

Something like the current SDK, using a dictionary internaly, so we can check is some attribute existe ou even have somethin like:

```
object.GetAttributeValue<T>("name")
or
object["name"] ;
```
Returning de default T value if the attribute dosen't exist.

Thanks!

**Comment by davidyack** [comment]
The C# library supports returning typed objects e.g.    var result = Get<MyContact>("contacts"...

Then you are fully typed, there are some issues though that arise due to the naming constructs of formatted fields

If you want to stay dynamic but have more helpers, I do have a companion helper class that I should see about putting up in the examples

**Comment by RafaelCavazza** [comment]
> The C# library supports returning typed objects e.g. var result = Get("contacts"...

I've seen the typed method and it works great, but for some scenarios we can't use a typed object.

> If you want to stay dynamic but have more helpers, I do have a companion helper class that I should see about putting up in the examples`

That would be great. The only drawback of the dynamic type is that i can't check if a field exists without raising an exception or using reflection.

I've build a custom function to return the result as a collection of `Dictionary<string,object> `so i can check whether any property exists, but it would be great to have this kind of helper in the Api.

Thanks!

**Comment by davidyack** [comment]
You actually can just cast the result to  IDictionary<string, object> you don't have to have it returned as a Dictionary - the Expando that is used by default supports that interface

**Comment by RafaelCavazza** [comment]
> You actually can just cast the result to IDictionary<string, object> you don't have to have it returned as a Dictionary - the Expando that is used by default supports that interface

Didn't thought about this... it worked perfectly!

Saved me many lines kkk.

Thanks!
