### ISSUE TITLE
The query parameter $fetchXml is not supported

### ISSUE THREAD

**Issue by ryanmichaeljames** [davidyack/Xrm.Tools.CRMWebAPI#62]
I getting the following error

> The query parameter $fetchXml is not supported

 It happens when I set any other `CRMGetListOptions` along with the `FetchXml` option. 

```
var results = await _api.GetList("lmnz_memberships", new CRMGetListOptions
{
    FetchXml = fetchXml,
    IncludeCount = true
});
```

If I only set `FetchXml ` it works.

```
var results = await _api.GetList("lmnz_memberships", new CRMGetListOptions
{
    FetchXml = fetchXml,
});
```

I believe is has to do with the `firstParam` variable in the `CRMWebAPI` class (line 763).

```
if (firstParam)
    fullurl = fullurl + string.Format("?fetchXml={0}", Uri.EscapeUriString(queryOptions.FetchXml));
else
    fullurl = fullurl + string.Format("&$fetchXml={0}", Uri.EscapeUriString(queryOptions.FetchXml));
```

Out of curiosity, what is the reason for the `firstParam` variable?

Thanks!

**Comment by davidyack** [comment]
Most options wont work in conjunction with FetchXml but you are right that should not have the $ in front of it, will get that updated.  the firstParam is just used to determine if appending ? or &

**Comment by ryanmichaeljames** [comment]
Thanks! 👍
