### ISSUE TITLE
Creating a Lookup to existing entity

### ISSUE THREAD

**Issue by StewUK** [davidyack/Xrm.Tools.CRMWebAPI#65]
Hi

I am trying to create an entity, but give it a lookup to an existing entity.

Is this possible? Currently the Create is also trying to generate the lookup entity, which fails as a key already exists.

Thanks

**Comment by davidyack** [comment]
Can you show some code - how are you setting the lookup reference?

**Comment by StewUK** [comment]
`dynamic newCustomEntity = new ExpandoObject();
newCustomEntity.value1 = "blah";
newCustomEntity.value2 = "anotherblah";

dynamic primaryContact = new ExpandoObject();
primaryContact.contactid = Guid.Parse(contactIdParameter);

newCustomEntity.contactlookup_id = primaryContact;

var result = await crmAPI.Create("new_customentity", newCustomEntity);  `

**Comment by StewUK** [comment]
Hi @davidyack just wondered if you had any ideas about this? I'd rather stick with your solution than go with the full framework and the SDK.

My goal is to create a child entity, then link it to a parent entity. Is there a better way to achieve this?

Thanks in advance

**Comment by davidyack** [comment]
Sorry I missed the notification on your prior message - if the contact already exists your contactlookup_id needs to have a value more like "/contacts(guid)"  assuming contactlookup_id is in fact your correct navigation property and contact is an existing record
