### ISSUE TITLE
Formatted values are not being retrieved while retrieving more than 5000 records

### ISSUE THREAD

**Issue by hemanth8424** [davidyack/Xrm.Tools.CRMWebAPI#68]
Hi,

While retrieving a large set of records via the GetList method, **FormattedValues** are returned for only 5000 records.

Please do consider this for the next enhancement.

Thanks,
Hemanth

**Comment by davidyack** [comment]
Thanks for pointing this out - it has been fixed and will be in the .20 version when it is published
