### ISSUE TITLE
GetList results in NullReference

### ISSUE THREAD

**Issue by alberto-martinbelloso** [davidyack/Xrm.Tools.CRMWebAPI#74]
I'm trying to create a CRMWebAPI from the bearer token in a .Net Core 2.0 project. The token looks good:

_{"token_type":"Bearer","expires_in":"3599","ext_expires_in":"3599","expires_on":"1543417370","not_before":"1543413470","resource":"https://xxxxxx.crm.dynamics.com","access_token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IndVTG1ZZnNxZFF1V3RWXy1oeFZ0REpKWk00USIsImtpZCI6IndVTG1ZZnNxZFF1V3RWXy1oeFZ0REpKWk00USJ9.eyJhdWQiOiJodHRwczovL2ltcG5kMy5jcm00LmR5bmFtaWNzLmNvbSIsImlzcyI6Imh0dHBzOi8vc ........"}_

`CRMWebAPI api = new CRMWebAPI(API_URL, bearer_token);`
`    var results = await api.GetList("accounts", new CRMGetListOptions() { Top=5,FormattedValues=true});`

But when I try to execute the previous code it crashes with the following exception:

_{System.NullReferenceException: Object reference not set to an instance of an object.    at Xrm.Tools.WebAPI.CRMWebAPI.EnsureSuccessStatusCode(HttpResponseMessage response, String jsonData)    at Xrm.Tools.WebAPI.CRMWebAPI.GetList(String uri, CRMGetListOptions QueryOptions) ..._

Any suggestion? 
Thanks in advance

**Comment by davidyack** [comment]
Two things I would check

1) confirm you are using the full url when you setup CRMWebAPI e.g
CRMWebAPI("https://orgname.api.crm.dynamics.com/api/data/v9.0/",
                    "<token>");
2) try your token in Postman by doing a get on the accounts entity passing that token in the authentication header - if it works there the token is good and then it is something with the setup of your url

**Comment by alberto-martinbelloso** [comment]
Thanks for your quick reply. 
I'm getting _HTTP Error 401 - Unauthorized: Access is denied_ on Postman with the token - I guess it has to be something about the Azure configuration.

**Comment by davidyack** [comment]
I would check to make sure you are getting the token with the right resource/authority 

AuthenticationParameters ap = AuthenticationParameters.CreateFromResourceUrlAsync(
                        new Uri("https://mydomain.crm.dynamics.com/api/data/")).Result;

String authorityUrl = ap.Authority;
String resourceUrl  = ap.Resource;

**Comment by davidyack** [comment]
Also make sure you have added permission to talk to Dynamics 365 on behalf of the user unless you are doing S2S

**Comment by alberto-martinbelloso** [comment]
authorityUrl looks like: 
      _-   https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/oauth2/authorize_
and resource url:
      _-   https://xxxxx.crm4.dynamics.com/_

When executing the c# script I get 401 as mentioned before, but if I copy the authority Url to the browser it says: **The request body must contain the following parameter: 'client_id'.**

Permissions also looks fine.

**Comment by davidyack** [comment]
Can you share an example of the code you are using?

**Comment by alberto-martinbelloso** [comment]
Here is the code I'm using:

            var getTokenTask = Task.Run(async () => await GetToken());
            Task.WaitAll(getTokenTask);

            if (getTokenTask.Result == null) return;
            string bearer_token = getTokenTask.Result;

            CRMWebAPI api = new CRMWebAPI(API_URL, bearer_token);
            try
            {
                var results = await api.GetList("accounts", new CRMGetListOptions() { Top = 5, FormattedValues = true });
            }
            catch (Exception ex)
            {
                throw ex;
            }

And here is the function that returns the bearer token:

            public static async Task<string> GetToken() 
            {
                  using (HttpClient httpClient = new HttpClient())
                        {
                            var formContent_credentials = new FormUrlEncodedContent(new[]
                            {
                                new KeyValuePair<string, string>("resource", Resource),
                                new KeyValuePair<string, string>("client_id", ClientId),
                                new KeyValuePair<string, string>("client_secret", ClientSecret),
                                new KeyValuePair<string, string>("grant_type", "client_credentials")
                            });

                            HttpResponseMessage response = await httpClient.PostAsync(Authority, formContent_credentials);

                            return !response.IsSuccessStatusCode ? null
                                : response.Content.ReadAsStringAsync().Result;
                        }
                    }

**Comment by davidyack** [comment]
oh it definitely is https://github.com/AzureAD/azure-activedirectory-library-for-dotnet
