### ISSUE TITLE
Missing reference

### ISSUE THREAD

**Issue by PederBennedsen** [davidyack/Xrm.Tools.CRMWebAPI#75]
I have installed CRMWebAPI and the demo-code, but my VS project can't find 'ClientCredential' and "AutenticationContext'.
What am I missing?
(I'm on Azure functions, .NET Core 2.0, VS 2017, CRMWebAPI 1.0.22 alpha)

**Comment by davidyack** [comment]
Sounds like you are missing references to ADAL libs do you have Microsoft.IdentityModel.Clients.ActiveDirectory added to your nuget packages?

**Comment by PederBennedsen** [comment]
After adding the package it works. Thanks.
