### ISSUE TITLE
URL is not encoded

### ISSUE THREAD

**Issue by NileshMoradiya** [davidyack/Xrm.Tools.CRMWebAPI#80]
Please add a patch to encode URL especially filter.

**Comment by AshV** [comment]
@NileshMoradiya could you please elaborate? where to add patch?

**Comment by NileshMoradiya** [comment]
@AshV On each filter to query string translation, take a look at snippet.

![image](https://user-images.githubusercontent.com/4757071/59579996-02322380-90ed-11e9-9cd0-3d40b2e378a0.png)

**Comment by davidyack** [comment]
I don't think we will add that now as it would change others existing use of filter where they have added their own url encoding like you show in your picture
