### ISSUE TITLE
edmProperty should be CrmEdmStructuralProperty

### ISSUE THREAD

**Issue by EkoZuluDev** [davidyack/Xrm.Tools.CRMWebAPI#82]
Hello David and other CRMWEBApi users!, 

Suddenly today we are experiencing this error when associating records. Have you seen this error message before? A google search does not yield results.

Edit: It happens when associating records with the systemusers entity

`  api.Associate(D365CEMetaData.CollectionNames.hhp_afspraaks, guidId, "ownerid", D365CEMetaData.CollectionNames.systemusers, ownerid);`

Thanks!

**Comment by EkoZuluDev** [comment]
MSFT broke the API after they updated our D365CE instances. 

Associating still works with CRMWebApi associate method but associating with the systemuser entity requires a different approach.

```
 public async Task<bool> PBS_Associate(string fromEntityCollection, Guid fromEntityID, string navProperty, string toEntityCollection, Guid toEntityID)
        {
            await CheckAuthToken();

            var fullUrl = _crmWebAPIConfig.APIUrl + fromEntityCollection + $"({fromEntityID})";

            HttpRequestMessage request = new HttpRequestMessage(new HttpMethod("PATCH"), fullUrl);

            var jsonData = $"{{ '{navProperty}@odata.bind': '{_crmWebAPIConfig.APIUrl}{toEntityCollection}({toEntityID})' }}";

            request.Content = new StringContent(jsonData, Encoding.UTF8, "application/json");

            var response = await _httpClient.SendAsync(request);

            EnsureSuccessStatusCode(response, jsonData: jsonData);

            return true;
        }


```

**Comment by davidyack** [comment]
Is there a reason you aren't using update to set owner?

**Comment by EkoZuluDev** [comment]
I was not aware that was possible, David. 

Is it possible to associate entities on create?  for example when I create a new account I want to associate it with a contact.

**Comment by davidyack** [comment]
Yes, couple of examples here https://github.com/davidyack/Xrm.Tools.CRMWebAPI/wiki/Create-Examples

**Comment by EkoZuluDev** [comment]
Thank you, Issue can close now!
