### ISSUE TITLE
FetchXml with between condition on a date value

### ISSUE THREAD

**Issue by EkoZuluDev** [davidyack/Xrm.Tools.CRMWebAPI#85]
Hi, 

I'm getting a "System.AggregateException","message":"One or more errors occurred. (Invalid URI: The Uri scheme is too long.)"

When trying to use the between condition. Has anyone encountered this issue before?

I'm using the public Task<CRMGetListResult<ExpandoObject>> GetList(string uri, CRMGetListOptions QueryOptions = null); method with a fetchxml which not large in character size. 

if I remove the between condition it works and I'm getting a result.

In the fetchXmlBuilder tool I'm getting my desired results fine.

**Comment by EkoZuluDev** [comment]
I will close this issue. It seems that the way FetchXmlBuilder processes FetchXml is different than CRMWebApi. I will investigate this further.

**Comment by davidyack** [comment]
@EkoZuluDev  I'm reopening for now, I'm curios why it would run on Fetch builder and not via the API - can you try via the portal here https://www.cds.tools/WebAPI - if you select the entity, you should be able to paste the fetch xml into the fetchxml tab and have it run

If it doesn't work it would be great if you could share an example of what fetchxml you have

**Comment by AshV** [comment]
If fetchXml is very large HTTP 414 (RequestURI too long) error will be thrown if executing it with WebAPI GET. Larger fetchXml should be executed with POST. Please have a look at https://stackoverflow.com/questions/41654161/request-url-too-long-for-fetchxml-query-types

**Comment by davidyack** [comment]
Yes, if it is a large FetchXML that is currently on the backlog to handle

**Comment by EkoZuluDev** [comment]
I think its size was the culprit. Reduced size of fetch xml by adjusting conditions, selected attributes and stripping the fetchxml from whitespaces before calling the API.
