### ISSUE TITLE
How do I request other annotations

### ISSUE THREAD

**Issue by wintg-zns** [davidyack/Xrm.Tools.CRMWebAPI#89]
In C#, CRMGetListOptions.FormattedValues boolean adds the following header to the request:
"Prefer", "odata.include-annotations=\\"OData.Community.Display.V1.FormattedValue\\""

I need to get the logical name of lookup objects, the @Microsoft.Dynamics.CRM.lookuplogicalname annotation.

How can I request other/multiple annotations to be included by the API in my request?

**Comment by davidyack** [comment]
This has now been merged @wintg-zns  thanks for helping!

**Comment by davidyack** [comment]
BTW will be in nuget version 1.0.25
