### ISSUE TITLE
{"error":{"code":"0x8006088a","message":"Bad Request - Error in query syntax.","innererror":{"message":"Bad Request - Error in query 

### ISSUE THREAD

**Issue by bpt2010** [davidyack/Xrm.Tools.CRMWebAPI#92]
When I try to Patch an entity either using the API or Post Man I am getting the following

XXXXX_twiliosmsid is an alternate key.  Not sure what am I doing wrong. 

Here is my Patch URL: 

```
PATCH /api/data/v9.1/XXXXX_smses(XXXXX_twiliosmsid='SM6861ee911ec847a78645f52f8187f7b1') HTTP/1.1
Host: XXXXX.crm.dynamics.com
OData-MaxVersion: 4.0
OData-Version: 4.0
Content-Type: application/json
Authorization: Bearer  eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IkJCOENlRlZxeWFHckdOdWVoSklpTDRkZmp6dyIsImtpZCI6IkJCOENlRlZxeWFHckdOdWVoSklpTDRkZmp6dyJ9.eyJhdWQiOiJodHRwczovL25hY2Nhc2Rldi5jcm0uZHluYW1pY3MuY29tIiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvNmM0MWE0ZTYtYjg5Ny00ZTZjLTgzMGUtMDFiZTJlNmIyOTI5LyIsImlhdCI6MTU3NjI2MTA4MywibmJmIjoxNTc2MjYxMDgzLCJleHAiOjE1NzYyNjQ5ODMsImFjciI6IjEiLCJhaW8iOiI0MlZnWUppMDE3N3hlK3VqZXpZdGNuWVIxL1A1elV6M3pua25aYWsveFhxelhzbWJMRGtBIiwiYW1yIjpbInB3ZCJdLCJhcHBpZCI6ImFkZTY0NDczLTJkN2QtNDc5ZS05MjMxLTFmOGM2ZTU0NjdkNyIsImFwcGlkYWNyIjoiMSIsImZhbWlseV9uYW1lIjoiQ29uZG9uIiwiZ2l2ZW5fbmFtZSI6IlRvbSIsImlwYWRkciI6IjcwLjEwNi4yNDQuMjI0IiwibmFtZSI6IlRvbSBDb25kb24iLCJvaWQiOiI2YjE4YzkyNC0yYTFkLTRhYmYtYjEwMS1mNWNlYjU4OGI0YWEiLCJwdWlkIjoiMTAwMzIwMDAzODJFRTlEOCIsInNjcCI6InVzZXJfaW1wZXJzb25hdGlddvbiIsInN1YiI6InJUdEJQWVBVTkMwLVZZY2h4akl3WkVFa3hlNmV3VzBpaWt4YTJvalFPSFEiLCJ0aWQiOiI2YzQxYTRlNi1iODk3LTRlNmMtODMwZS0wMWJlMmU2YjI5MjkiLCJ1bmlxdWVfbmFtZSI6InRjb25kb25ATkFDQ0FTTkdPLm9ubWljcm9zb2Z0LmNvbSIsInVwbiI6InRjb25kb25ATkFDQ0FTTkdPLm9ubWljcm9zb2Z0LmNvbSIsInV0aSI6Im1pOHZ0dEYyU2syNDIxcTVoWUlVQUEiLCJ2ZXIiOiIxLjAiLCJ3aWRzIjpbIjYyZTkwMzk0LTY5ZjUtNDIzNy05MTkwLTAxMjE3NzE0NWUxMCJdfQ.P8wVBKnzQgu-2CrowtjlQdRtR9WflwZANgs-Uf2XD9mSdH8xVzZ_LncXmD0lLbpzSVr9H9PSX4C7Lpo8tPI_zQoN_7aLVh4epUPcENMWoY-7iXQRl1apr69d5Ftx9t8us4-7JtZzW-XVsNSYTuszEWdOVIG5uT3m2kxIY2xHXhGnbvQL-jVEfsgKFZ8VHzj86LZtZQbeb-ccvyAYNx3n2S2TOYld4OkET6S3muH5asTa8J4L8wcKa4b4arkrVSo3aQ5ev92ybYs8Jkezbim9pyUTvFKB4RTI5CQKFQmhzCkfaev3UGKffmEdHJyDpQarEjsYjTkAYIiIDeJL1jPsbg

Accept: application/json
```

`{"error":{"code":"0x8006088a","message":"Bad Request - Error in query syntax.","innererror":{"message":"Bad Request - Error in query syntax.","type":"Microsoft.OData.ODataException","stacktrace":"   at Microsoft.OData.UriParser.ODataUriResolver.ResolveKeys(IEdmEntityType type, IDictionary`2 namedValues, Func`3 convertFunc)\r\n   at Microsoft.OData.UriParser.AlternateKeysODataUriResolver.ResolveKeys(IEdmEntityType type, IDictionary`2 namedValues, Func`3 convertFunc)\r\n   at Microsoft.OData.UriParser.SegmentArgumentParser.TryConvertValues(IEdmEntityType targetEntityType, IEnumerable`1& keyPairs, ODataUriResolver resolver)\r\n   at Microsoft.OData.UriParser.SegmentKeyHandler.CreateKeySegment(ODataPathSegment segment, KeySegment previousKeySegment, SegmentArgumentParser key, ODataUriResolver resolver)\r\n   at Microsoft.OData.UriParser.SegmentKeyHandler.TryCreateKeySegmentFromParentheses(ODataPathSegment previous, KeySegment previousKeySegment, String parenthesisExpression, ODataUriResolver resolver, ODataPathSegment& keySegment, Boolean enableUriTemplateParsing)\r\n   at Microsoft.OData.UriParser.ODataPathParser.TryBindKeyFromParentheses(String parenthesesSection)\r\n   at Microsoft.OData.UriParser.ODataPathParser.TryCreateSegmentForNavigationSource(String identifier, String parenthesisExpression)\r\n   at Microsoft.OData.UriParser.ODataPathParser.CreateFirstSegment(String segmentText)\r\n   at Microsoft.OData.UriParser.ODataPathParser.ParsePath(ICollection`1 segments)\r\n   at Microsoft.OData.UriParser.ODataPathFactory.BindPath(ICollection`1 segments, ODataUriParserConfiguration configuration)\r\n   at Microsoft.OData.UriParser.ODataUriParser.Initialize()\r\n   at System.Web.OData.Routing.DefaultODataPathHandler.Parse(String serviceRoot, String odataPath, IServiceProvider requestContainer, Boolean template)\r\n   at System.Web.OData.Routing.DefaultODataPathHandler.Parse(String serviceRoot, String odataPath, IServiceProvider requestContainer)\r\n   at Microsoft.Crm.Extensibility.ODataV4.Routing.CrmODataPathHandler.Parse(String serviceRoot, String odataPath, IServiceProvider requestContainer)"}}}`

**Comment by davidyack** [comment]
@bpt2010  so it looks like you are trying to do an update by alternate key?  Have you confirmed that key is properly setup and also that you are posting well formed data for the fields you are updating?

**Comment by bpt2010** [comment]
Hi David,

Thanks for responding. Yes its using an alternate key. Everything was setup correctly but in the code I was referencing the alternate key name instead of the field name. After updating the code to use the field name. It worked. 

Thanks
